/*==============================================================================*/
/* Copyright (C) 2014 JSL Technology. All right reserved.						*/
/* Tittle: Ethernet Register													*/
/* Comment:																		*/
/*==============================================================================*/

#ifndef __J_ETHERNET_REG__
#define __J_ETHERNET_REG__


/* GMAC */
#define EMAC_MAC_CONFIGURATION      	0x00
#define EMAC_MAC_FRAME_FILTER       	0x04
#define EMAC_GMII_ADDRESS       		0x10
#define EMAC_GMII_DATA  				0x14
#define EMAC_FLOW_CONTROL        		0x18
#define EMAC_VLAN_TAG        			0x1C
#define EMAC_VERSION 	     			0x20
#define EMAC_DEBUG   					0x24
#define EMAC_LPI_CONTROL_STATUS     	0x30
#define EMAC_LPI_TIMERS_CONTROL     	0x34
#define EMAC_INTERRUPT_STATUS       	0x38
#define EMAC_INTERRUPT_MASK   			0x3C
#define EMAC_MAC_ADDRESS_HIGH(n)		(0x40+(n*4))
#define EMAC_MAC_ADDRESS_LOW(n)			(0x44+(n*4))
#define EMAC_SGMII_RGMII_SMII_CONTROL_STATUS	0xD8
#define EMAC_MMC_CONTROL         		0x100
#define EMAC_MMC_RECEIVE_INTERRUPT    	0x104
#define EMAC_MMC_TRANSMIT_INTERRUPT     0x108
#define EMAC_MMC_RECEIVE_INTERRUPT_MASK 	0x10C
#define EMAC_MMC_TRANSMIT_INTERRUPT_MASK    0x110
#define EMAC_TXOCTETCOUNT_GB         	0x114
#define EMAC_TXFRAMECOUNT_GB   			0x118
#define EMAC_TXBROADCASTFRAMES_G   		0x11C
#define EMAC_TXMULTICASTFRAMES_G   		0x120
#define EMAC_TX64OCTETS_GB   			0x124
#define EMAC_TX65TO127OCTETS_GB   		0x128
#define EMAC_TX128TO255OCTETS_GB   		0x12C
#define EMAC_TX256TO511OCTETS_GB   		0x130
#define EMAC_TX512TO1023OCTETS_GB   	0x134
#define EMAC_TX1024TOMAXOCTETS_GB   	0x138
#define EMAC_TXUNICASTFRAMES_GB   		0x13C
#define EMAC_TXMULTICASTFRAMES_GB   	0x140
#define EMAC_TXBROADCASTFRAMES_GB   	0x144
#define EMAC_TXUNDERFLOWERROR   		0x148
#define EMAC_TXSINGLECOL_G   			0x14C
#define EMAC_TXMULTICOL_G   			0x150
#define EMAC_TXDEFERRED   				0x154
#define EMAC_TXLATECOL   				0x158
#define EMAC_TXEXESSCOL  				0x15C
#define EMAC_TXCARRIERERR  				0x16C
#define EMAC_TXOCTETCNT   				0x164
#define EMAC_TXFRAMECOUNT_G   			0x168
#define EMAC_TXEXCESSDEF   				0x16C
#define EMAC_TXPAUSEFRAMES   			0x170
#define EMAC_TXVLANFRAMES_G   			0x174
#define EMAC_TXOVERSIZE_G   			0x178
#define EMAC_RXFRAMECOUNT_GB   			0x180
#define EMAC_RXOCTETCOUNT_GB   			0x184
#define EMAC_RXOCTETCOUNT_G   			0x188
#define EMAC_RXBROADCASTFRAMES_G   		0x18C
#define EMAC_RXMULTICASTFRAMES_G   		0x190
#define EMAC_RXCRCERROR   				0x194
#define EMAC_RXALIGNMENTERROR   		0x198
#define EMAC_RXRUNTERROR   				0x19C
#define EMAC_RXJABBERERROR   			0x1A0
#define EMAC_RXUNDERSIZE_G   			0x1A4
#define EMAC_RXOVERSIZE_G   			0x1A8
#define EMAC_RX64OCTETS_GB   			0x1AC
#define EMAC_RX65TO127OCTETS_GB   		0x1B0
#define EMAC_RX128TO255OCTETS_GB   		0x1B4
#define EMAC_RX256TO511OCTETS_GB   		0x1B8
#define EMAC_RX512TO1023OCTETS_GB   	0x1BC
#define EMAC_RX1024TOMAXOCTETS_GB   	0x1C0
#define EMAC_RXUNICASTFRAMES_G   		0x1C4
#define EMAC_RXLENGTHERROR   			0x1C8
#define EMAC_RXOUTOFRANGETYPE   		0x1CC
#define EMAC_RXPAUSEFRAMES   			0x1D0
#define EMAC_RXFIFOOVERFLOW   			0x1D4
#define EMAC_RXVLANFRAMES_GB   			0x1D8
#define EMAC_RXWATCHDOGERROR   			0x1DC
#define EMAC_RXRCVERROR   				0x1E0
#define EMAC_RXCTRLFRAMES_G   			0x1E4
#define EMAC_MMC_IPC_RECEIVE_INTERRUPT_MASK	0x200
#define EMAC_MMC_IPC_RECEIVE_INTERRUPT	0x208
#define EMAC_RXIPV4_GD_FRMS   			0x210
#define EMAC_RXIPV4_HDRERR_FRMS   		0x214
#define EMAC_RXIPV4_NOPAY_FRMS   		0x218
#define EMAC_RXIPV4_FRAG_FRMS   		0x21C
#define EMAC_RXIPV4_UDSBL_FRMS   		0x220
#define EMAC_RXIPV6_GD_FRMS   			0x224
#define EMAC_RXIPV6_HDRERR_FRMS   		0x228
#define EMAC_RXIPV6_NOPAY_FRMS   		0x22C
#define EMAC_RXUDP_GD_FRMS   			0x230
#define EMAC_RXUDP_ERR_FRMS   			0x234
#define EMAC_RXTCP_GD_FRMS   			0x238
#define EMAC_RXTCP_ERR_FRMS   			0x23C
#define EMAC_RXICMP_GD_FRMS   			0x240
#define EMAC_RXICMP_ERR_FRMS   			0x244
#define EMAC_RXIPV4_GD_OCTETS   		0x250
#define EMAC_RXIPV4_HDRERR_OCTETS   	0x254
#define EMAC_RXIPV4_NOPAY_OCTETS   		0x258
#define EMAC_RXIPV4_FRAG_OCTETS   		0x25C
#define EMAC_RXIPV4_UDSBL_OCTETS   		0x260
#define EMAC_RXIPV6_GD_OCTETS   		0x264
#define EMAC_RXIPV6_HDRERR_OCTETS   	0x268
#define EMAC_RXIPV6_NOPAY_OCTETS   		0x26C
#define EMAC_RXUDP_GD_OCTETS   			0x270
#define EMAC_RXUDP_ERR_OCTETS   		0x274
#define EMAC_RXTCP_GD_OCTETS   			0x278
#define EMAC_RXTCPERROCTETS   			0x27C
#define EMAC_RXICMP_GD_OCTETS   		0x280
#define EMAC_RXICMP_ERR_OCTETS  		0x284
#define EMAC_L3_L4_CONTROL(n)   		(0x400+(n*0x30))
#define EMAC_LAYER4_ADDRESS(n)   		(0x404+(n*0x30))
#define EMAC_LAYER3_ADDR0_REG(n)   		(0x410+(n*0x30))
#define EMAC_LAYER3_ADDR1_REG(n)  		(0x414+(n*0x30))
#define EMAC_LAYER3_ADDR2_REG(n)  		(0x418+(n*0x30))
#define EMAC_LAYER3_ADDR3_REG(n)   		(0x41C+(n*0x30))
#define EMAC_HASH_TABLE_REG(n)  		(0x500+(n*4))
#define EMAC_VLAN_INCL_REG   			0x584
#define EMAC_VLAN_HASH_TABLE_REG  		0x588
#define EMAC_TIMESTAMP_CONTROL 			0x700
#define EMAC_SUB_SECOND_INCREMENT 		0x704
#define EMAC_SYSTEM_TIME_SECONDS 		0x708
#define EMAC_SYSTEM_TIME_NANOSECONDS 		0x70C
#define EMAC_SYSTEM_TIME_SECONDS_UPDATE		0x710
#define EMAC_SYSTEM_TIME_NANOSECONDS_UPDATE	0x714
#define EMAC_TIMESTAMP_ADDEND			0x718
#define EMAC_TARGET_TIME_SECONDS		0x71C
#define EMAC_TARGET_TIME_NANOSECONDS	0x720
#define EMAC_SYSTEM_TIME_HIGHER_WORD_SECONDS	0x724
#define EMAC_TIMESTAMP_STATUS			0x728
#define EMAC_PPS_CONTROL				0x72C
#define EMAC_AUXILIARY_TIMESTAMP_NANOSECONDS	0x730
#define EMAC_AUXILIARY_TIMESTAMP_SECONDS	0x734
#define EMAC_PPS0_INTERVAL				0x760
#define EMAC_PPS0_WIDTH					0x764
#define EMAC_MAC_ADDRESS16_HIGH(n)		(0x800+(n*8))
#define EMAC_MAC_ADDRESS16_LOW(n)		(0x804+(n*8))

/* DMA */
#define EMAC_BUS_MODE					0x1000
#define EMAC_TRANSMIT_POLL_DEMAND		0x1004
#define EMAC_RECEIVE_POLL_DEMAND		0x1008
#define EMAC_RECEIVE_DESCRIPTOR_LIST_ADDRESS	0x100C
#define EMAC_TRANSMIT_DESCRIPTOR_LIST_ADDRESS	0x1010
#define EMAC_STATUS						0x1014
#define EMAC_OPERATION_MODE				0x1018
#define EMAC_INTERRUPT_ENABLE			0x101C
#define EMAC_MISSED_FRAME_AND_BUFFER_OVERFLOW_COUNTER	0x1020
#define EMAC_RECEIVE_INTERRUPT_WATCHDOG_TIMER	0x1024
#define EMAC_AXI_BUS_MODE				0x1028
#define EMAC_AHB_OR_AXI_STATUS			0x102C
#define EMAC_CURRENT_HOST_TRANSMIT_DESCRIPTOR	0x1048
#define EMAC_CURRENT_HOST_RECEIVE_DESCRIPTOR	0x104C
#define EMAC_CURRENT_HOST_TRANSMIT_BUFFER_ADDRESS	0x1050
#define EMAC_CURRENT_HOST_RECEIVE_BUFFER_ADDRESS	0x1054
#define EMAC_HW_FEATURE					0x1058

/* PHY Standard Register */
#define	EPHY_CTRL					0
#define	EPHY_STATUS					1
#define	EPHY_ID1					2
#define	EPHY_ID2					3
#define	EPHY_AN_ADV					4
#define	EPHY_AN_LINK				5
#define	EPHY_AN_EXP					6
#define	EPHY_1000BT_CONTROL			9
#define	EPHY_1000BT_STATUS			10
#define	EPHY_VENDOR					16
#define	EPHY_MODE_CTRL				17
#define	EPHY_SPECIAL				27
#define	EPHY_INT_STAT				29
#define	EPHY_INT_MASK				30
#define	EPHY_SPECIAL_CTRL			31

#endif /* __J_ETHERNET_REG__ */









