/*
 * typedefine.h
 *
 *  Created on: 2018/01/25
 *      Author: suzuki-hiroyuki
 */

#ifndef SRC_INCLUDE_TYPEDEFINE_H_
#define SRC_INCLUDE_TYPEDEFINE_H_

/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Thu, Oct 04, 2007                                     */
/*  DESCRIPTION :Aliases of Integer Type                               */
/*  CPU TYPE    :SH7203                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/

#define	_PTR		void *
#define	_AND		,
#define	_NOARGS		void
#define	_CONST		const
#define	_VOLATILE	volatile
#define	_SIGNED		signed
#define	_DOTS		, ...
#define _VOID void
#define FUNC(x)		(*((void (**)(void)) x ))	/*	関数のポインタのアドレス指定	*/

/*<< 								>>*/
typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed int _SINT;
typedef unsigned int _UINT;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
typedef signed long long _SQWORD;
typedef unsigned long long _UQWORD;

/* volatile 符号無し */
typedef	volatile unsigned char    vu8;
typedef volatile unsigned short   vu16;
typedef volatile unsigned int     vu32;

/* #define UB	unsigned char */
#define DBL_SGL	float /* double/float */

/**
 * @ Status type definition
 */
typedef enum {ERROR = 0, SUCCESS = !ERROR} Status;
#endif /* SRC_INCLUDE_TYPEDEFINE_H_ */
