// getdt.c
#include <stdio.h>
#include <string.h>
#include "alt_cache.h"
#include "pl/pl.h"
#define EXT
#include "global.h"
#include "com_ram.c"
#include "cis_ram.c"
#include "cis_calibration.h"

extern const unsigned char template_data[];
extern const unsigned char software_ver[64];

/*ヘッダー情報設定関数*/
void parameter_set(ST_BS *tmp_pbs)
{
	u8 cnt = 0;
	u8 cnt2 = 0;
	u8 d[8];
	u32 data = 0;

	#if 0//#if defined(PRJ_IVIZION2)
	ST_PLANE_INFOMATION_DATA plane_info_data[] =
	{
		{UP_R_R,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_R_OFFSET},
		{UP_R_G,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_G_OFFSET},
		{UP_R_B,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_B_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_B_OFFSET},
		{UP_R_IR1,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_IR1_OFFSET},
		{UP_R_IR2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISA_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISA_R_IR2_OFFSET},
#if POINT_UV1_ENABLE && POINT_UV2_ENABLE
		{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				8,				1,					SUB_PITCH_25DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_25DPI,	CISA_R_UV_OFFSET},
#elif POINT_UV1_ENABLE && !POINT_UV2_ENABLE
		{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				8,				9,					SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_UV_OFFSET},
#elif CIS_UV_ENABLE
		{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_FL_OFFSET},
#else
		{UP_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
#endif
		{DOWN_R_R,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_R_OFFSET},
		{DOWN_R_G,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_G_OFFSET},
		{DOWN_R_B,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_B_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_B_OFFSET},
		{DOWN_R_IR1,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_IR1_OFFSET},
		{DOWN_R_IR2,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISB_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISB_R_IR2_OFFSET},
#if POINT_UV1_ENABLE && POINT_UV2_ENABLE
		{DOWN_R_FL,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	1,					8,				8,				9,					SUB_PITCH_25DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_25DPI,	CISB_R_UV_OFFSET},
#elif POINT_UV1_ENABLE && !POINT_UV2_ENABLE
		{DOWN_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
#elif CIS_UV_ENABLE
		{DOWN_R_FL,		REFLECTION,	DOWN,	PLANE_DISABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_R_FL_OFFSET},
#else
		{DOWN_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
#endif
		{DOWN_T_R,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_R_OFFSET},
		{DOWN_T_G,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISB_T_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISB_T_G_OFFSET},
		{DOWN_T_IR1,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_IR1_OFFSET},
		{DOWN_T_IR2,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_IR2_OFFSET},
#if MAG1_ENABLE
		{UP_MAG,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				9,				16,					SUB_PITCH_50DPI,	0,						CIS_DATA_TYPE,	0,	16,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_MAG1_OFFSET},
		{UP_MAG2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					10,				11,				16,					SUB_PITCH_50DPI,	0,						CIS_DATA_TYPE,	0,	16,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_MAG2_OFFSET},
#endif
		{MAX_PLANE_COUNT, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	};
	#endif

	//2023-07-19
	// UBA700 UV, MAG無効
	ST_PLANE_INFOMATION_DATA plane_info_data_uba700[] =
	{
		{UP_R_R,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_R_OFFSET},
		{UP_R_G,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_G_OFFSET},
		{UP_R_B,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_B_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_B_OFFSET},
		{UP_R_IR1,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_IR1_OFFSET},
		{UP_R_IR2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISA_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISA_R_IR2_OFFSET},
	//#if POINT_UV1_ENABLE && POINT_UV2_ENABLE
	//	{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				8,				1,					SUB_PITCH_25DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_25DPI,	CISA_R_UV_OFFSET},
	//#elif POINT_UV1_ENABLE && !POINT_UV2_ENABLE
	//	{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				8,				9,					SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_UV_OFFSET},
	//#elif CIS_UV_ENABLE
	//	{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_FL_OFFSET},
	//#else
		{UP_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
	//#endif
		{DOWN_R_R,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_R_OFFSET},
		{DOWN_R_G,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_G_OFFSET},
		{DOWN_R_B,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_B_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_B_OFFSET},
		{DOWN_R_IR1,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_IR1_OFFSET},
		{DOWN_R_IR2,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISB_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISB_R_IR2_OFFSET},
	//#if POINT_UV1_ENABLE && POINT_UV2_ENABLE
	//	{DOWN_R_FL,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	1,					8,				8,				9,					SUB_PITCH_25DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_25DPI,	CISB_R_UV_OFFSET},
	//#elif POINT_UV1_ENABLE && !POINT_UV2_ENABLE
	//	{DOWN_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
	//#elif CIS_UV_ENABLE
	//	{DOWN_R_FL,		REFLECTION,	DOWN,	PLANE_DISABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_R_FL_OFFSET},
	//#else
		{DOWN_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
	//#endif
		{DOWN_T_R,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_R_OFFSET},
		{DOWN_T_G,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISB_T_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISB_T_G_OFFSET},
		{DOWN_T_IR1,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_IR1_OFFSET},
		{DOWN_T_IR2,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_IR2_OFFSET},
	//#if MAG1_ENABLE
	//	{UP_MAG,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				9,				16,					SUB_PITCH_50DPI,	0,						CIS_DATA_TYPE,	0,	16,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_MAG1_OFFSET},
	//	{UP_MAG2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					10,				11,				16,					SUB_PITCH_50DPI,	0,						CIS_DATA_TYPE,	0,	16,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_MAG2_OFFSET},
	//#endif
		{MAX_PLANE_COUNT, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	};

	// UBA700 UV, MAG有効
	ST_PLANE_INFOMATION_DATA plane_info_data_uba710[] =
	{
		{UP_R_R,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_R_OFFSET},
		{UP_R_G,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_G_OFFSET},
		{UP_R_B,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_B_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_B_OFFSET},
		{UP_R_IR1,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISA_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISA_R_IR1_OFFSET},
		{UP_R_IR2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISA_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISA_R_IR2_OFFSET},
	//#if POINT_UV1_ENABLE && POINT_UV2_ENABLE
		{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				8,				1,					SUB_PITCH_25DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_25DPI,	CISA_R_UV_OFFSET},
	//#elif POINT_UV1_ENABLE && !POINT_UV2_ENABLE
	//	{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				8,				9,					SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_UV_OFFSET},
	//#elif CIS_UV_ENABLE
	//	{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_FL_OFFSET},
	//#else
	//	{UP_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
	//#endif
		{DOWN_R_R,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_R_OFFSET},
		{DOWN_R_G,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_G_OFFSET},
		{DOWN_R_B,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_B_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_B_OFFSET},
		{DOWN_R_IR1,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_200DPI,	CISB_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_200DPI,	CISB_R_IR1_OFFSET},
		{DOWN_R_IR2,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISB_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISB_R_IR2_OFFSET},
	//#if POINT_UV1_ENABLE && POINT_UV2_ENABLE
		{DOWN_R_FL,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	1,					8,				8,				9,					SUB_PITCH_25DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	9,					0,	0,	0,	0,	PERIOD_25DPI,	CISB_R_UV_OFFSET},
	//#elif POINT_UV1_ENABLE && !POINT_UV2_ENABLE
	//	{DOWN_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
	//#elif CIS_UV_ENABLE
	//	{DOWN_R_FL,		REFLECTION,	DOWN,	PLANE_DISABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISB_AREA_MAX,	CISB_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_R_FL_OFFSET},
	//#else
	//	{DOWN_R_FL,		0,			0,		PLANE_DISABLED,	0,		0,					0,				0,				0,					0,					0,						0,				0,	0,					0,	0,	0,	0,	0,				0},
	//#endif
		{DOWN_T_R,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_R_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_R_OFFSET},
		{DOWN_T_G,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_100DPI,	CISB_T_G_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_100DPI,	CISB_T_G_OFFSET},
		{DOWN_T_IR1,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_IR1_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_IR1_OFFSET},
		{DOWN_T_IR2,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN,	CISA_AREA_MAX,	CISA_MAIN_OFFSET,	SUB_PITCH_50DPI,	CISB_T_IR2_SUB_OFFSET,	CIS_DATA_TYPE,	0,	CIS_MAIN_ALL_PIXS,	0,	0,	0,	0,	PERIOD_50DPI,	CISB_T_IR2_OFFSET},
	//#if MAG1_ENABLE
		{UP_MAG,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					8,				9,				16,					SUB_PITCH_50DPI,	0,						CIS_DATA_TYPE,	0,	16,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_MAG1_OFFSET},
		{UP_MAG2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	1,					10,				11,				16,					SUB_PITCH_50DPI,	0,						CIS_DATA_TYPE,	0,	16,					0,	0,	0,	0,	PERIOD_50DPI,	CISA_R_MAG2_OFFSET},
	//#endif
		{MAX_PLANE_COUNT, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	};


	work[0].pbs = tmp_pbs;

	memset(tmp_pbs, 0, ALL_INFO_SIZE);

	/*ファイル情報*/
	tmp_pbs->version = FILE_FORMAT_VERSION;	//バージョン
	tmp_pbs->file_size = FILE_SIZE;			//最大ファイルサイズ
#if defined(UBA)
	tmp_pbs->model_code[0] = 0x34;			//TODO:機種コード(4128)
	tmp_pbs->model_code[1] = 0x31;
	tmp_pbs->model_code[2] = 0x32;
	tmp_pbs->model_code[3] = 0x38;
#else
	tmp_pbs->model_code[0] = 0x34;			//TODO:機種コード(4126)
	tmp_pbs->model_code[1] = 0x31;
	tmp_pbs->model_code[2] = 0x32;
	tmp_pbs->model_code[3] = 0x36;
#endif

	tmp_pbs->spec_code.mode = 0;
	tmp_pbs->spec_code.sensor_conf = 0;
#if defined(UBA)
	//bit0:Point-UV, bit1:CIS-UV, bit2:MAG1, bit3:MAG2, bit4-6:other, bit7:Position adjustment,
	tmp_pbs->spec_code.model_calibration = (u16)((POSITION_ENABLE << 7)
												+ (OTHER6_ENABLE << 6)
												+ (OTHER5_ENABLE << 5)
												+ (OTHER4_ENABLE << 4)
//												+ (MAG1_ENABLE << 3)
												+ (ex_uba710 << 3)
												+ (ex_uba710 << 2)
												+ (ex_uba710 << 1)
												+ (CIS_UV_ENABLE << 0));
#else
	//bit0:Point-UV, bit1:CIS-UV, bit2:MAG1, bit3:MAG2, bit4-6:other, bit7:Position adjustment,
	tmp_pbs->spec_code.model_calibration = (u16)((POSITION_ENABLE << 7)
												+ (OTHER6_ENABLE << 6)
												+ (OTHER5_ENABLE << 5)
												+ (OTHER4_ENABLE << 4)
												+ (MAG1_ENABLE << 3)
												+ (POINT_UV2_ENABLE << 2)
												+ (POINT_UV1_ENABLE << 1)
												+ (CIS_UV_ENABLE << 0));
#endif

	tmp_pbs->LEorSE = SE;										//ロングエッジ ／ショートエッジ
	tmp_pbs->Blocksize = BLOCK_SIZE;							//1ブロックあたりのサブブロック数
	tmp_pbs->Subblock_dpi = SUB_BLOCK_DPI;						//サブブロックのdpi
	tmp_pbs->Blockbytesize = BLOCK_BYTE_SIZE;					//ブロックサイズ
	tmp_pbs->pitch_ratio = (float)TRANS_CORRECT_PITCH;			//搬送ピッチ補正値

	for(cnt = 0; cnt < MAX_PLANE_COUNT; cnt++)
	{
	#if defined(UBA) //2023-07-18
		if(ex_uba710 == 1)
		{
			if(plane_info_data_uba710[cnt].plane_num == MAX_PLANE_COUNT)
			{
				break;
			}
			memcpy(&tmp_pbs->PlaneInfo[plane_info_data_uba710[cnt].plane_num], &plane_info_data_uba710[cnt].PlaneInfo, sizeof(ST_PLANE_INFOMATION));
		}
		else
		{
			if(plane_info_data_uba700[cnt].plane_num == MAX_PLANE_COUNT)
			{
				break;
			}
			memcpy(&tmp_pbs->PlaneInfo[plane_info_data_uba700[cnt].plane_num], &plane_info_data_uba700[cnt].PlaneInfo, sizeof(ST_PLANE_INFOMATION));
		}
	#else
		if(plane_info_data[cnt].plane_num == MAX_PLANE_COUNT)
		{
			break;
		}
		memcpy(&tmp_pbs->PlaneInfo[plane_info_data[cnt].plane_num], &plane_info_data[cnt].PlaneInfo, sizeof(ST_PLANE_INFOMATION));
	#endif
	}

	for(cnt = 0; cnt < 10; cnt++)
	{
		tmp_pbs->template_ver[cnt] = template_data[0x0C + cnt];
	}
	for(cnt = 0; cnt < 12; cnt++)
	{
		tmp_pbs->unit_ser[cnt] = ex_adjustment_data.factory_info.serial_no[cnt];
	}

	for(cnt = 0; cnt < 64; cnt++)
	{
		if((software_ver[cnt] == 0x56) && (software_ver[cnt+4] == 0x2d))
		{
			for(cnt2 = 0; cnt2 < 7; cnt2++)
			{
				tmp_pbs->soft_ver[cnt2] = software_ver[cnt+cnt2];
			}
			break;
		}
	}

	if(get_pl_state())
	{
		for(cnt = 0; cnt < sizeof(d); cnt++)
		{
			d[cnt] = 0;
		}
		data = FPGA_REG.FVER.LWORD;
		d[0] = (u8)((data & 0xF0000000) >> 28);
		d[1] = (u8)((data & 0x0F000000) >> 24);
		d[2] = (u8)((data & 0x00F00000) >> 20);
		d[3] = (u8)((data & 0x000F0000) >> 16);
		d[4] = (u8)((data & 0x0000F000) >> 12);
		d[5] = (u8)((data & 0x00000F00) >>  8);
		d[6] = (u8)((data & 0x000000F0) >>  4);
		d[7] = (u8)((data & 0x0000000F) >>  0);
		for(cnt = 0; cnt < 8; cnt++)
		{
			if((0x0A <= d[cnt]) && (d[cnt] <= 0x0F))
			{
				tmp_pbs->fpga_ver[cnt] = d[cnt] - 0x0A + 0x41;
			}
			else
			{
				tmp_pbs->fpga_ver[cnt] = d[cnt] + 0x30;
			}
		}
	}

	_kernel_synch_cache();
}

/*ヘッダー情報設定関数*/
void parameter_set_raw_cis(ST_BS *tmp_pbs)
{
	u8 cnt = 0;
	u8 cnt2 = 0;
	u8 d[8];
	u32 data = 0;
	/*プレーン情報テーブル*/
	ST_PLANE_INFOMATION_DATA plane_info_data_raw[] = {
		{UP_R_R,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISA_R_R_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISA_R_R_OFFSET_RAW},
		{UP_R_G,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISA_R_G_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISA_R_G_OFFSET_RAW},
		{UP_R_B,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISA_R_B_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISA_R_B_OFFSET_RAW},
		{UP_R_IR1,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISA_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISA_R_IR1_OFFSET_RAW},
		{UP_R_IR2,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_100DPI,	CISA_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_100DPI_RAW,	CISA_R_IR2_OFFSET_RAW},
		{UP_R_FL,		REFLECTION,	UP,		PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_50DPI,	CISA_R_FL_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_50DPI_RAW,	CISA_R_FL_OFFSET_RAW},
		{DOWN_R_R,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN_RAW,	CISB_AREA_MAX_RAW,	CISB_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISB_R_R_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISB_R_R_OFFSET_RAW},
		{DOWN_R_G,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN_RAW,	CISB_AREA_MAX_RAW,	CISB_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISB_R_G_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISB_R_G_OFFSET_RAW},
		{DOWN_R_B,		REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN_RAW,	CISB_AREA_MAX_RAW,	CISB_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISB_R_B_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISB_R_B_OFFSET_RAW},
		{DOWN_R_IR1,	REFLECTION,	DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN_RAW,	CISB_AREA_MAX_RAW,	CISB_MAIN_OFFSET_RAW,	SUB_PITCH_200DPI,	CISB_R_IR1_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_200DPI_RAW,	CISB_R_IR1_OFFSET_RAW},
		{DOWN_R_IR2,	REFLECTION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN_RAW,	CISB_AREA_MAX_RAW,	CISB_MAIN_OFFSET_RAW,	SUB_PITCH_100DPI,	CISB_R_IR2_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_100DPI_RAW,	CISB_R_IR2_OFFSET_RAW},
		{DOWN_R_FL,		REFLECTION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISB_AREA_MIN_RAW,	CISB_AREA_MAX_RAW,	CISB_MAIN_OFFSET_RAW,	SUB_PITCH_50DPI,	CISB_R_FL_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_50DPI_RAW,	CISB_R_FL_OFFSET_RAW},
		{DOWN_T_R,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_50DPI,	CISB_T_R_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_50DPI_RAW,	CISB_T_R_OFFSET_RAW},
		{DOWN_T_G,		TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_100DPI,	CISB_T_G_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_100DPI_RAW,	CISB_T_G_OFFSET_RAW},
		{DOWN_T_IR1,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_50DPI,	CISB_T_IR1_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_50DPI_RAW,	CISB_T_IR1_OFFSET_RAW},
		{DOWN_T_IR2,	TRANSMISSION,DOWN,	PLANE_ENABLED,	L2R,	CIS_MAIN_PITCH,		CISA_AREA_MIN_RAW,	CISA_AREA_MAX_RAW,	CISA_MAIN_OFFSET_RAW,	SUB_PITCH_50DPI,	CISB_T_IR2_SUB_OFFSET,	CIS_DATA_TYPE_RAW,	0,	CIS_MAIN_ALL_PIXS_RAW,	0,	0,	0,	0,	PERIOD_50DPI_RAW,	CISB_T_IR2_OFFSET_RAW},
		{MAX_PLANE_COUNT, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	};

	work[0].pbs = tmp_pbs;

	/*ファイル情報*/
	tmp_pbs->version = FILE_FORMAT_VERSION;
	tmp_pbs->file_size = FILE_SIZE_RAW;
	tmp_pbs->model_code[0] = 0x34;			//TODO:機種コード(0000)
	tmp_pbs->model_code[1] = 0x31;
	tmp_pbs->model_code[2] = 0x32;
	tmp_pbs->model_code[3] = 0x36;

	tmp_pbs->spec_code.mode = 0;
	tmp_pbs->spec_code.sensor_conf = 0;

#if defined(UBA)
	//bit0:Point-UV, bit1:CIS-UV, bit2:MAG1, bit3:MAG2, bit4-6:other, bit7:Position adjustment,
	tmp_pbs->spec_code.model_calibration = (u16)((POSITION_ENABLE << 7)
												+ (OTHER6_ENABLE << 6)
												+ (OTHER5_ENABLE << 5)
												+ (OTHER4_ENABLE << 4)
												+ (ex_uba710 << 3)
												+ (ex_uba710 << 2)
												+ (ex_uba710 << 1)
												+ (CIS_UV_ENABLE << 0));

#else
	//bit0:Point-UV, bit1:CIS-UV, bit2:MAG1, bit3:MAG2, bit4-6:other, bit7:Position adjustment,
	tmp_pbs->spec_code.model_calibration = (u16)((POSITION_ENABLE << 7)
												+ (OTHER6_ENABLE << 6)
												+ (OTHER5_ENABLE << 5)
												+ (OTHER4_ENABLE << 4)
												+ (MAG1_ENABLE << 3)
												+ (POINT_UV2_ENABLE << 2)
												+ (POINT_UV1_ENABLE << 1)
												+ (CIS_UV_ENABLE << 0));
#endif

	tmp_pbs->LEorSE = SE;
	tmp_pbs->Blocksize = SUB_BLOCK_NUM;
	tmp_pbs->Subblock_dpi = SUB_BLOCK_DPI;
	tmp_pbs->Blockbytesize = BLOCK_BYTE_SIZE_RAW;
	tmp_pbs->pitch_ratio = (float)PITCH;

	for (cnt = 0; cnt < MAX_PLANE_COUNT; cnt++) {
		if (plane_info_data_raw[cnt].plane_num == MAX_PLANE_COUNT) {
			break;
		}
		memcpy(&tmp_pbs->PlaneInfo[plane_info_data_raw[cnt].plane_num], &plane_info_data_raw[cnt].PlaneInfo, sizeof(ST_PLANE_INFOMATION));
	}

	for(cnt = 0; cnt < 10; cnt++)
	{
		tmp_pbs->template_ver[cnt] = template_data[0x0C + cnt];
	}
	for(cnt = 0; cnt < 12; cnt++)
	{
		tmp_pbs->unit_ser[cnt] = ex_adjustment_data.factory_info.serial_no[cnt];
	}

	for(cnt = 0; cnt < 64; cnt++)
	{
		if((software_ver[cnt] == 0x56) && (software_ver[cnt+4] == 0x2d))
		{
			for(cnt2 = 0; cnt2 < 7; cnt2++)
			{
				tmp_pbs->soft_ver[cnt2] = software_ver[cnt+cnt2];
			}
			break;
		}
	}

	if(get_pl_state())
	{
		for(cnt = 0; cnt < sizeof(d); cnt++)
		{
			d[cnt] = 0;
		}
		data = FPGA_REG.FVER.LWORD;
		d[0] = (u8)((data & 0xF0000000) >> 28);
		d[1] = (u8)((data & 0x0F000000) >> 24);
		d[2] = (u8)((data & 0x00F00000) >> 20);
		d[3] = (u8)((data & 0x000F0000) >> 16);
		d[4] = (u8)((data & 0x0000F000) >> 12);
		d[5] = (u8)((data & 0x00000F00) >>  8);
		d[6] = (u8)((data & 0x000000F0) >>  4);
		d[7] = (u8)((data & 0x0000000F) >>  0);
		for(cnt = 0; cnt < 8; cnt++)
		{
			if((0x0A <= d[cnt]) && (d[cnt] <= 0x0F))
			{
				tmp_pbs->fpga_ver[cnt] = d[cnt] - 0x0A + 0x41;
			}
			else
			{
				tmp_pbs->fpga_ver[cnt] = d[cnt] + 0x30;
			}
		}
	}

	_kernel_synch_cache();
}
