#ifndef _SRC_MAIN_INCLUDE_CIS_RAM_H		/* prevent circular inclusions */
#define _SRC_MAIN_INCLUDE_CIS_RAM_H		/* by using protection macros */
#include "debug.h"
#include "memorymap.h"
#include "struct.h"

#if defined(EXT)
	#define EXTERN extern
#else
	#undef EXTERN
	#define EXTERN
#endif

enum
{
#if (_DEBUG_CIS_MULTI_IMAGE==1)
	ADJDAT_ADDR = ADJDAT_ADDR_BASE,
	ROWDAT_ADDR = ROWDAT_ADDR_BASE,
	BILL_NOTE_IMAGE_TOP = BILL_NOTE_IMAGE_TOP_BASE,
#else
	ADJDAT_ADDR = 0x05000000,
	ROWDAT_ADDR = 0x05800000,
	BILL_NOTE_IMAGE_TOP = 0x06000000,

	IMAGEDAT_SIZE	 = 0x02000000,
	ADJDAT_SIZE =  0x00800000,
	ROWDAT_SIZE =  0x00800000,
#endif
};
#if (_DEBUG_CIS_MULTI_IMAGE==1)
typedef enum
{
	CIS_IMAGE_UNKNOWN = 0,
	CIS_IMAGE_INITIALIZED,
	CIS_IMAGE_USED
} CIS_BUFFER_STATUS;
#define BILL_NOTE_IMAGE_MAX_COUNT 4
typedef struct CIS_IMAGE_CONTROL
{
	u32	current;
	u32	last;
	CIS_BUFFER_STATUS image_status[BILL_NOTE_IMAGE_MAX_COUNT];
}CIS_IMAGE_CONTROL;
EXTERN CIS_IMAGE_CONTROL ex_cis_image_control;
#endif

EXTERN CIS_ADJUSTMENT_DATA ex_cis_adjustment_data;
EXTERN CIS_ADJUSTMENT_TMP ex_cis_adjustment_tmp;
EXTERN CIS_ADJUSTMENT_PGA ex_calc_pga;
EXTERN BC_DATA ex_calc_bc;
//EXTERN ADJ_SENSOR_DATA ex_adj_data;
//EXTERN ROW_SENSOR_DATA ex_row_data;
#define ex_adj_data (*(volatile ADJ_SENSOR_DATA *)(ADJDAT_ADDR))
#define ex_row_data (*(volatile ROW_SENSOR_DATA *)(ROWDAT_ADDR))
#define ex_tmp_mag_data (*(volatile MAG_SENSOR_DATA *)(ROWDAT_ADDR))
#define ex_tmp_validation_data (*(volatile TMP_VALIDATION_SENSOR_DATA *)(ROWDAT_ADDR))
EXTERN TMP_AD_TBL ex_tmp_ad_data;
EXTERN TMP_10BIT_AD_TBL ex_tmp_10bit_ad_data;

EXTERN u32 tmp_x[720];
EXTERN u32 tmp_y[720];

//#define CIS_DATA_BASE_ADDR	0x06100000
/************************** Constant Definitions ****************************/
enum CIS_SIDE
{
	OUTSIDE,
	INSIDE
};
enum LED_NO
{
	LED_BLK,		// 0
	RLS_RED,		// 1
	RLS_GRE,		// 2
	RLS_BLU,		// 3
	RLS_IR1,		// 4
	RLS_IR2,		// 5
	RLS_FL,			// 6
	TLS_RED,		// 7
	TLS_GRE,		// 8
	TLS_IR1,		// 9
	TLS_IR2,		// 10

	LED_END
};
enum BLACK_NO
{
	BLACK_NO_1,			// 0
	BLACK_NO_2,			// 1

	BLACK_NO_END
};
enum SEN_NO
{
	SEN_NO_BLK,			// 0
	SEN_NO_RLS_RED,		// 1
	SEN_NO_RLS_GRE,		// 2
	SEN_NO_RLS_BLU,		// 3
	SEN_NO_RLS_IR1,		// 4
	SEN_NO_RLS_IR2,		// 5
	SEN_NO_RLS_FL,		// 6
	SEN_NO_TLS_RED,		// 7
	SEN_NO_TLS_GRE,		// 8
	SEN_NO_TLS_IR1,		// 9
	SEN_NO_TLS_IR2,		// 10

	SEN_NO_END
};
/********************************************************************************************************/
/*			New FPGA																					*/
/*			2020/03/31																					*/
/********************************************************************************************************/
#define FPGA_BASEADDR (0xFF200000)

#define FPGA_ADDR_REG		(FPGA_BASEADDR + 0x00000)	// FPGA制御レジスタ, 19/05/15
#define FPGA_ADDR_CAPINFO	(FPGA_BASEADDR + 0x02000)	// 採取データ情報
#define FPGA_ADDR_CISSEQ	(FPGA_BASEADDR + 0x05000)	// 識別センサーシーケンス設定
#define FPGA_ADDR_SSSEQ		(FPGA_BASEADDR + 0x06000)	// 識別センサーシーケンス設定(CIS以外)
#define FPGA_ADDR_SSPITDAT	(FPGA_BASEADDR + 0x08000)	// SPI送信データ
#define FPGA_ADDR_SSPIRDAT	(FPGA_BASEADDR + 0x08800)	// 予約（SPI受信データ）
#define FPGA_ADDR_RUARTTDAT	(FPGA_BASEADDR + 0x09000)	// RFID-UART送信データ
#define FPGA_ADDR_RUARRTDAT	(FPGA_BASEADDR + 0x09800)	// RFID-UART受信データ
#define FPGA_ADDR_DACDAT	(FPGA_BASEADDR + 0x0B000)	// DAC設定
#define FPGA_ADDR_MOTPRM	(FPGA_BASEADDR + 0x0C000)	// モーター制御パラメータ
#define FPGA_ADDR_CISEDG	(FPGA_BASEADDR + 0x0D000)	// CIS2値化エッジ情報
#define FPGA_ADDR_CISMLT	(FPGA_BASEADDR + 0x0E000)	// CIS重券検出情報・設定
#define FPGA_ADDR_CISCMPAB	(FPGA_BASEADDR + 0x20000)	// CIS補正テーブル CISA 黒補正
#define FPGA_ADDR_CISCMPAW	(FPGA_BASEADDR + 0x28000)	// CIS補正テーブル CISA 白補正
#define FPGA_ADDR_CISCMPBB	(FPGA_BASEADDR + 0x30000)	// CIS補正テーブル CISB 黒補正
#define FPGA_ADDR_CISCMPBW	(FPGA_BASEADDR + 0x38000)	// CIS補正テーブル CISB 白補正

#define FPGA_REG (*(volatile FPGA_REG_STRUCT *)FPGA_ADDR_REG)
#define FPGA_DAC_REG (*(volatile DACDAT_REG_STRUCT *)FPGA_ADDR_DACDAT)
#define FPGA_MOTPRM_REG (*(volatile MOTPRM_REG_STRUCT *)FPGA_ADDR_MOTPRM)


/* FPGA_ADDR_CAPINFO */
//#define CAP_INFO_ARRAY		(*(volatile CAP_INFO_ARRAY_ST *)(FPGA_ADDR_CAPINFO))	// 識別センサシーケンス配列(CIS)

/* Seqence Register */
#define BV_CISSEQ_ARRAY		(*(volatile BV_CISSEQ_ARRAY_ST *)(FPGA_ADDR_CISSEQ))	// 識別センサシーケンス配列(CIS), 19/05/23
#define BV_SSSEQ_ARRAY		(*(volatile BV_SSSEQ_ARRAY_ST *)(FPGA_ADDR_SSSEQ))	// 識別センサシーケンス配列(CIS以外), 19/05/23

/* CIS2値化エッジ情報 CIS重券検出情報・設定 */
#define BV_CISEDG_ARRAY		(*(volatile BV_CISEDG_ARRAY_ST *)(FPGA_ADDR_CISEDG))
#define BV_CISMLT_ARRAY		(*(volatile BV_CISMLT_ARRAY_ST *)(FPGA_ADDR_CISMLT))


#define AFE_REGISTER_SIZE	(0x80 + 1)
#define EX_AFE_REGISTER		(*(volatile struct _AFE_REGISTER *)FPGA_ADDR_SSPITDAT)

#define CIS_AFE_CH0_PIXEL	0
#define CIS_AFE_CH1_PIXEL	288
#define CIS_AFE_CH2_PIXEL	576
#define CIS_AFE_MAX_PIXEL	720

#define CAP_INFO_BASE		FPGA_ADDR_CAPINFO		// 採取データ情報ベースアドレス, 19/12/10
#define BV_CISSEQ_BASE		FPGA_ADDR_CISSEQ		// 識別シーケンスレジスタベースアドレス,19/12/10
#define SSSEQ_REGISTER_SIZE	(4096)					/* レジスタサイズ */

#define CISCMPAB_REGISTER	(*(volatile struct _CISA_BLACK_STRUCT *)FPGA_ADDR_CISCMPAB)	// CIS補正テーブル CISA 黒補正
#define CISCMPAW_REGISTER	(*(volatile struct _CISA_WHITE_STRUCT *)FPGA_ADDR_CISCMPAW)	// CIS補正テーブル CISA 白補正
#define CISCMPBB_REGISTER	(*(volatile struct _CISB_BLACK_STRUCT *)FPGA_ADDR_CISCMPBB)	// CIS補正テーブル CISB 黒補正
#define CISCMPBW_REGISTER	(*(volatile struct _CISB_WHITE_STRUCT *)FPGA_ADDR_CISCMPBW)	// CIS補正テーブル CISB 白補正

//oneshot or sampling
enum{
	CAP_SAMPLING,
	CAP_ONE_SHOT_8BIT,
	CAP_ONE_SHOT_10BIT,
	CAP_ONE_SHOT_TMP_10BIT,
	CAP_ONE_SHOT_MAG,
	CAP_ONE_SHOT_CHECK_CIS,
};

//sampling address period offset
#define CAP_PLANE_ADDRESS_PERIOD_UP_R_R				5112
#define CAP_PLANE_ADDRESS_PERIOD_UP_R_G				5112
#define CAP_PLANE_ADDRESS_PERIOD_UP_R_IR1			5112
#define CAP_PLANE_ADDRESS_PERIOD_UP_R_IR2			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_R_R			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_R_G			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_R_IR1			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_R_IR2			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_T_R			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_T_G			5112
#define CAP_PLANE_ADDRESS_PERIOD_DOWN_T_IR1			5112

/**************************************************************************************/
#define ONESHOT_ADDRESS_OFFSET_UP_R_R				0
#define ONESHOT_ADDRESS_OFFSET_UP_R_G				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 1)
#define ONESHOT_ADDRESS_OFFSET_UP_R_B				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 2)
#define ONESHOT_ADDRESS_OFFSET_UP_R_IR1				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 3)
#define ONESHOT_ADDRESS_OFFSET_UP_R_IR2				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 4)
#define ONESHOT_ADDRESS_OFFSET_UP_R_FL				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 5)
#define ONESHOT_ADDRESS_OFFSET_RESERVE1				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 6)//P_Reserve1
#define ONESHOT_ADDRESS_OFFSET_RESERVE2				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 7)//P_Reserve2
#define ONESHOT_ADDRESS_OFFSET_RESERVE4				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 8)//P_Reserve4
#define ONESHOT_ADDRESS_OFFSET_RESERVE5				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 9)//P_Reserve5
#define ONESHOT_ADDRESS_OFFSET_DOWN_R_R				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 10)
#define ONESHOT_ADDRESS_OFFSET_DOWN_R_G				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 11)
#define ONESHOT_ADDRESS_OFFSET_DOWN_R_B				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 12)
#define ONESHOT_ADDRESS_OFFSET_DOWN_R_IR1			((HDRTBL_SIZE + MAIN_SCAN_LINE) * 13)
#define ONESHOT_ADDRESS_OFFSET_DOWN_R_IR2			((HDRTBL_SIZE + MAIN_SCAN_LINE) * 14)
#define ONESHOT_ADDRESS_OFFSET_DOWN_R_FL			((HDRTBL_SIZE + MAIN_SCAN_LINE) * 15)
#define ONESHOT_ADDRESS_OFFSET_DOWN_T_R				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 16)
#define ONESHOT_ADDRESS_OFFSET_DOWN_T_G				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 17)
#define ONESHOT_ADDRESS_OFFSET_DOWN_T_IR1			((HDRTBL_SIZE + MAIN_SCAN_LINE) * 18)
#define ONESHOT_ADDRESS_OFFSET_DOWN_T_IR2			((HDRTBL_SIZE + MAIN_SCAN_LINE) * 19)

#define ONESHOT_ADDRESS_10BIT_OFFSET_UP_R_R			0
#define ONESHOT_ADDRESS_10BIT_OFFSET_UP_R_G			((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 1)
#define ONESHOT_ADDRESS_10BIT_OFFSET_UP_R_B			((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 2)
#define ONESHOT_ADDRESS_10BIT_OFFSET_UP_R_IR1		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 3)
#define ONESHOT_ADDRESS_10BIT_OFFSET_UP_R_IR2		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 4)
#define ONESHOT_ADDRESS_10BIT_OFFSET_UP_R_FL		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 5)
#define ONESHOT_ADDRESS_10BIT_OFFSET_RESERVE1		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 6)//P_Reserve1
#define ONESHOT_ADDRESS_10BIT_OFFSET_RESERVE2		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 7)//P_Reserve2
#define ONESHOT_ADDRESS_10BIT_OFFSET_RESERVE4		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 8)//P_Reserve4
#define ONESHOT_ADDRESS_10BIT_OFFSET_RESERVE5		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 9)//P_Reserve5
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_R_R		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 10)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_R_G		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 11)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_R_B		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 12)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_R_IR1		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 13)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_R_IR2		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 14)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_R_FL		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 15)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_T_R		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 16)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_T_G		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 17)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_T_IR1		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 18)
#define ONESHOT_ADDRESS_10BIT_OFFSET_DOWN_T_IR2		((HDRTBL_SIZE_10BIT + MAIN_SCAN_LINE) * 2 * 19)

//MAG sampling
#define ONESHOT_ADDRESS_MAG_OFFSET_MAG				0

/**************************************************************************************/
/* Use cis as a position */
#define CHECK_CIS_ADDRESS_OFFSET_1ST				0
#define CHECK_CIS_ADDRESS_OFFSET_2ED				((HDRTBL_SIZE + MAIN_SCAN_LINE) * 1)
/**************************************************************************************/

#define ADDRESS_OFFSET_BCWC_R_R			0
#define ADDRESS_OFFSET_BCWC_R_G			9
#define ADDRESS_OFFSET_BCWC_R_B			18
#define ADDRESS_OFFSET_BCWC_R_IR1		27
#define ADDRESS_OFFSET_BCWC_R_IR2		36
#define ADDRESS_OFFSET_BCWC_R_FL		45
#define ADDRESS_OFFSET_BCWC_T_R			54
#define ADDRESS_OFFSET_BCWC_T_G			63
#define ADDRESS_OFFSET_BCWC_T_IR1		72
#define ADDRESS_OFFSET_BCWC_T_IR2		81

// シーケンステーブルの構成(MSB 4bits:サイクル数, LSB 4bits:テーブル数)
#define CYCTBL_CYC_VALUE			0x4
#define CYCTBL_TBL_VALUE			0x4

/* AFE define */
#define BANKCNTRL_VALUE				0x00
//#define CNTRL_VALUE					0x95
#define CNTRL_VALUE					0xD5	//<-0x95
#define SHG0_VALUE					0x00	//0x00[x1],			0x07[x2]
#define OFFDAC00_VALUE				0x0A	//0x0A[case x1],	0x05[case x2]	0x02[case x3 not used]
#define OFFDAC01_VALUE				0x0A	//0x0A[case x1],	0x05[case x2]	0x02[case x3 not used]
#define OFFDAC02_VALUE				0x0A	//0x0A[case x1],	0x05[case x2]	0x02[case x3 not used]
#define OFFDAC03_VALUE				0x0A	//0x0A[case x1],	0x05[case x2]	0x02[case x3 not used]
#define DGAIN00_VALUE				0x20	//0x20[x1],			0x40[x2],		0x60[x3 not used]
#define DGAIN01_VALUE				0x20	//0x20[x1],			0x40[x2],		0x60[x3 not used]
#define DGAIN02_VALUE				0x20	//0x20[x1],			0x40[x2],		0x60[x3 not used]
#define DGAIN03_VALUE				0x20	//0x20[x1],			0x40[x2],		0x60[x3 not used]
#define OFFSET00_MSB_VALUE			0x00
#define OFFSET00_LSB_VALUE			0x00
#define OFFSET01_MSB_VALUE			0x00
#define OFFSET01_LSB_VALUE			0x00
#define OFFSET02_MSB_VALUE			0x00
#define OFFSET02_LSB_VALUE			0x00
#define OFFSET03_MSB_VALUE			0x00
#define OFFSET03_LSB_VALUE			0x00
#define OUTCTRL1_VALUE				0x00	//normal:0x00  adctest:0x04
#define OUTCTRL2_VALUE				0x08
#define OUTCTRL3_VALUE				0x32	//<-0x02 New FPGA
#define OUTCTRL4_VALUE				0x06
#define TRIG_VALUE					0x32	//<-0x12  //inv:1 en:1
#define TGOUT1_VALUE				0x24
#define TGOUT2_VALUE				0x23	//<-0x21
#define TGOUT3_VALUE				0x21	//<-0x23
#define PCISCKR_VALUE				0x00
#define PCISCKF_VALUE				0x15
#define PSHDF_VALUE					0x1E
#define LEDCTRL_VALUE				0x01
#define COUNT0_MSB_VALUE			0x01
#define COUNT0_LSB_VALUE			0x75	//<-0x72
#define COUNT1_MSB_VALUE			0x00
#define COUNT1_LSB_VALUE			0x00
#define COUNT2_MSB_VALUE			0x00
#define COUNT2_LSB_VALUE			0x00
#define LEDEN_RRISE1_MSB_VALUE		0x00
#define LEDEN_RRISE1_LSB_VALUE		0x01
#define LEDEN_RFALL1_MSB_VALUE		0x00
#define LEDEN_RFALL1_LSB_VALUE		0x46
#define LEDEN_RRISE2_MSB_VALUE		0x00
#define LEDEN_RRISE2_LSB_VALUE		0x00
#define LEDEN_RFALL2_MSB_VALUE		0x00
#define LEDEN_RFALL2_LSB_VALUE		0x00
#define LEDEN_RRISE3_MSB_VALUE		0x00
#define LEDEN_RRISE3_LSB_VALUE		0x00
#define LEDEN_RFALL3_MSB_VALUE		0x00
#define LEDEN_RFALL3_LSB_VALUE		0x00
#define LEDEN_RRISE4_MSB_VALUE		0x00
#define LEDEN_RRISE4_LSB_VALUE		0x00
#define LEDEN_RFALL4_MSB_VALUE		0x00
#define LEDEN_RFALL4_LSB_VALUE		0x00
#define LEDEN_GRISE1_MSB_VALUE		0x00
#define LEDEN_GRISE1_LSB_VALUE		0x01
#define LEDEN_GFALL1_MSB_VALUE		0x00
#define LEDEN_GFALL1_LSB_VALUE		0x46
#define LEDEN_GRISE2_MSB_VALUE		0x00
#define LEDEN_GRISE2_LSB_VALUE		0x00
#define LEDEN_GFALL2_MSB_VALUE		0x00
#define LEDEN_GFALL2_LSB_VALUE		0x00
#define LEDEN_GRISE3_MSB_VALUE		0x00
#define LEDEN_GRISE3_LSB_VALUE		0x00
#define LEDEN_GFALL3_MSB_VALUE		0x00
#define LEDEN_GFALL3_LSB_VALUE		0x00
#define LEDEN_GRISE4_MSB_VALUE		0x00
#define LEDEN_GRISE4_LSB_VALUE		0x00
#define LEDEN_GFALL4_MSB_VALUE		0x00
#define LEDEN_GFALL4_LSB_VALUE		0x00
#define LEDEN_BRISE1_MSB_VALUE		0x00
#define LEDEN_BRISE1_LSB_VALUE		0x00
#define LEDEN_BFALL1_MSB_VALUE		0x00
#define LEDEN_BFALL1_LSB_VALUE		0x00
#define LEDEN_BRISE2_MSB_VALUE		0x00
#define LEDEN_BRISE2_LSB_VALUE		0x00
#define LEDEN_BFALL2_MSB_VALUE		0x00
#define LEDEN_BFALL2_LSB_VALUE		0x00
#define LEDEN_BRISE3_MSB_VALUE		0x00
#define LEDEN_BRISE3_LSB_VALUE		0x00
#define LEDEN_BFALL3_MSB_VALUE		0x00
#define LEDEN_BFALL3_LSB_VALUE		0x00
#define LEDEN_BRISE4_MSB_VALUE		0x00
#define LEDEN_BRISE4_LSB_VALUE		0x00
#define LEDEN_BFALL4_MSB_VALUE		0x00
#define LEDEN_BFALL4_LSB_VALUE		0x00
#define SP2START_MSB_VALUE			0x00
#define SP2START_LSB_VALUE			0x00
#define SP2HWIDTH_MSB_VALUE			0x00
#define SP2HWIDTH_LSB_VALUE			0x00
#define SP2PERIOD_MSB_VALUE			0x00
#define SP2PERIOD_LSB_VALUE			0x00
#define SP2COUNT_VALUE				0x00
#define BOSRISE0_MSB_VALUE			0x00
#define BOSRISE0_LSB_VALUE			0x53	//<-0x52
#define BOSFALL0_MSB_VALUE			0x00
#define BOSFALL0_LSB_VALUE			0x54	//<-0x53
#define ENRISE_MSB_VALUE			0x00
#define ENRISE_LSB_VALUE			0x53	//<-0x52
#define ENFALL_MSB_VALUE			0x01
#define ENFALL_LSB_VALUE			0x73	//<-0x72
#define TRIGWIDTH_MSB_VALUE			0x00
#define TRIGWIDTH_LSB_VALUE			0x00
#define CISCK_MASK_START_MSB_VALUE	0x00
#define CISCK_MASK_START_LSB_VALUE	0x00
#define CISCK_MASK_END_MSB_VALUE	0x00
#define CISCK_MASK_END_LSB_VALUE	0x00
#define ISELR_VALUE					0x0D
#define ISELG_VALUE					0x0D
#define ISELB_VALUE					0x00
#define ADCK_CONTROL_VALUE			0x71
#define ADCK_PH_VALUE				0x5C

#define TLS_PIX_SARCH_MIN			105
#define TLS_PIX_SARCH_MAX			615

#define WHITE_CHIP_MIN_TMP_AD		50
// 最小温度補正係数
#define TMP_ADJUSTMENT_RATIO_MIN	0.1f// 理論上0.180392157が限界 46/255
// 最大温度補正係数
#define TMP_ADJUSTMENT_RATIO_MAX	2.0f
// 最大点灯時間
#define LED_TIME_MAX				2200
#define LED_TIME_MAX2				4600

#define EDGE_PAPER_CHECK_PIX_MIN		240
#define EDGE_PAPER_CHECK_PIX_MAX		480

#define EDGE_PAPER_CHECK_SKEW_THR		5.0f

#define EDGE_PAPER_CHECK_MLT_THR		0xB00 //クーポン3枚分で返却 2023-02-07 yuji

#define MAG_SAMPLING_DELAY				50	//50Block分手前からサンプリング
#define MAG_DATA_SHIFT					6	//MAGデータAD,CD方向の左右合わせデータシフト長

/* 補正シーケンス */
enum ADJUSTMENT_SEQUENCE
{
	ADJUSTMENT_PL_INIT,
	ADJUSTMENT_CIS_INIT,
	ADJUSTMENT_REGSTER_RESET,
	ADJUSTMENT_SAMPLING,
	ADJUSTMENT_DATA_CALCRATION,
	ADJUSTMENT_SEQUENCE_END,
};

typedef struct _VAL_WATCH
{
	u32 start;
	u32	end;
}VAL_WATCH;
EXTERN VAL_WATCH ex_val_watch;

EXTERN u32 ex_fpga_event_log_address;

#endif /* _SRC_MAIN_INCLUDE_CIS_RAM_H */
/* EOF */
